# Generated by Django 4.1.7 on 2023-05-02 06:13

import book.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='书名')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='标准书号')),
                ('thumbnail', models.FileField(upload_to=book.models.book_thumbnail_path, verbose_name='缩略图')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('publish_house', models.CharField(max_length=255, verbose_name='出版社')),
                ('publish_date', models.DateField(verbose_name='出版时间')),
                ('price', models.FloatField(verbose_name='价格')),
                ('pages', models.SmallIntegerField(verbose_name='页数')),
                ('stock', models.SmallIntegerField(default=0, verbose_name='库存')),
                ('add_date', models.DateField(verbose_name='添加时间')),
                ('intro', models.TextField(verbose_name='图书简介')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=255, unique=True, verbose_name='分类名')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '图书分类',
                'verbose_name_plural': '图书分类',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='收藏时间')),
                ('favorite_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_object', to='book.book', verbose_name='收藏对象')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to=settings.AUTH_USER_MODEL, verbose_name='收藏用户')),
            ],
        ),
        migrations.CreateModel(
            name='CarouselBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.FileField(upload_to=book.models.carousel_book_path, verbose_name='轮播图')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('describe', models.CharField(max_length=255, verbose_name='描述')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='关联图书')),
            ],
            options={
                'verbose_name': '推荐图书',
                'verbose_name_plural': '推荐图书',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='BookBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_time', models.DateTimeField(auto_now=True, verbose_name='借阅时间')),
                ('borrow_status', models.SmallIntegerField(choices=[(1, '借阅中'), (2, '已归还')], default=1, verbose_name='借阅状态')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_borrow_book', to='book.book', verbose_name='图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_borrow_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_category', to='book.bookcategory', verbose_name='所属分类'),
        ),
    ]
